#!/usr/bin/env node
/**
 * Modify one markdown file outside content/ with Claude: the automation
 * files (scripts/site-tree.md, scripts/scaffold-schedule.md, the predefined
 * pages in scripts/site-tree-content/) and the docs (README.md, CLAUDE.md…).
 * Pages under content/ go through scripts/edit-page.js instead, which knows
 * the template engine and the layouts.
 *
 *   node scripts/edit-md.js <file> "<instruction>"             edit it now
 *   node scripts/edit-md.js <file> "<instruction>" --dry-run   print the result, write nothing
 *   node scripts/edit-md.js --list                             list the files it can edit
 *
 * Options:
 *   --proposal-out=<file>    with --dry-run: also save the proposed file as JSON
 *                            ({ file, mode: "markdown", content, problems,
 *                            warnings, … }) at this path, so a tool can show it
 *                            and then write exactly that version.
 *
 * <file> is a path from the repository root, e.g. scripts/site-tree.md.
 * dist/, node_modules/ and CHANGELOG.md (generated by npm run changelog) are
 * never edited.
 *
 * Claude returns the complete file. "Problems" stop it being written: a reply
 * cut off at the token limit, an unclosed ``` fence, frontmatter that lost its
 * closing "---", a schedule job list that no longer parses, a site tree with
 * no pages left. "Warnings" (pages added to or removed from the tree, a job
 * list that changed size, a file that shrank by half) are printed but don't.
 * The file's line endings are kept.
 *
 * Requires ANTHROPIC_API_KEY.
 *
 * The Twinstack web app installs this file, with scripts/lib/schedule-jobs.js,
 * into site copies made before it existed. So it imports nothing else from
 * scripts/lib/ except ROOT and readJson, which every copy has, and keeps its
 * own API call and site-tree parser. lib/knowledge.js (the notes and work log
 * in knowledge/) is loaded only if the copy has it.
 */

import fs from 'node:fs';
import path from 'node:path';
import { ROOT, readJson } from './lib/content.js';
import { parseJobs } from './lib/schedule-jobs.js';

const knowledge = await import('./lib/knowledge.js').catch(() => null);

const MAX_TOKENS = 16000;
// Claude writes the whole file back, so it has to fit comfortably in one reply.
const MAX_FILE_BYTES = 40 * 1024;
const SKIPPED_DIRS = new Set(['content', 'dist', 'node_modules', 'static']);
const GENERATED = new Set(['CHANGELOG.md']);
const SCHEDULE_FILE = 'scripts/scaffold-schedule.md';
const TREE_FILE = 'scripts/site-tree.md';
const TREE_CONTENT_DIR = 'scripts/site-tree-content/';

const argv = process.argv.slice(2);
const flag = (name) => {
  const hit = argv.find((a) => a === `--${name}` || a.startsWith(`--${name}=`));
  if (!hit) return undefined;
  return hit.includes('=') ? hit.split('=').slice(1).join('=') : true;
};
const positional = argv.filter((a) => !a.startsWith('--'));
const dryRun = Boolean(flag('dry-run'));
const proposalOut = flag('proposal-out');

const site = readJson(path.join(ROOT, 'site.config.json'));
const apiKey = process.env.ANTHROPIC_API_KEY;

/* ------------------------------------------------------------ own helpers */

// ANTHROPIC_BASE_URL points at a proxy or a local mock, as in lib/claude-writer.js.
const API_URL = `${(process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com').replace(/\/+$/, '')}/v1/messages`;

/** One Messages API call: the reply text and why Claude stopped ("max_tokens" when cut off). */
async function requestClaude({ systemPrompt, userContent }) {
  const response = await fetch(API_URL, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({
      model: site.automation.model,
      max_tokens: MAX_TOKENS,
      system: systemPrompt,
      messages: [{ role: 'user', content: userContent }],
    }),
  });
  if (!response.ok) throw new Error(`Anthropic API ${response.status}: ${(await response.text()).slice(0, 400)}`);
  const payload = await response.json();
  const text = payload.content.filter((b) => b.type === 'text').map((b) => b.text).join('').trim();
  return { text, stopReason: payload.stop_reason ?? null };
}

function stripFence(text) {
  const fenced = text.match(/^```[a-z]*\n([\s\S]*)\n```$/);
  return fenced ? fenced[1] : text;
}

/** Page paths in a site tree: the same "- path.html [— instruction]" lines lib/scaffold-tree-runner.js reads. */
function treePaths(text) {
  const out = [];
  for (const raw of text.split('\n')) {
    const bullet = /^\s*-\s+(.*)$/.exec(raw.replace(/\r$/, ''));
    if (!bullet) continue;
    const split = /^(\S+)\s+(?:—|--)\s+(.*)$/.exec(bullet[1]);
    const rawPath = (split ? split[1] : bullet[1]).trim();
    if (rawPath.endsWith('.html')) out.push(rawPath);
  }
  return out;
}

/* ---------------------------------------------------------------- files */

/** Every markdown file this script may edit, as repo-relative paths. */
function editableFiles(dir = ROOT) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    const rel = path.relative(ROOT, full).split(path.sep).join('/');
    if (entry.isDirectory()) {
      if (!SKIPPED_DIRS.has(rel)) out.push(...editableFiles(full));
    } else if (entry.name.endsWith('.md') && !GENERATED.has(rel)) {
      out.push(rel);
    }
  }
  return out.sort();
}

/** The repo-relative file, or an error message saying why it can't be edited. */
function resolveTarget(arg) {
  const rel = path.posix.normalize(String(arg).replace(/\\/g, '/')).replace(/^\.\//, '');
  if (rel.startsWith('../') || rel === '..' || path.posix.isAbsolute(rel) || /^[A-Za-z]:/.test(rel)) {
    return { error: `"${arg}" is outside the repository.` };
  }
  if (!rel.endsWith('.md')) return { error: `"${rel}" isn't a markdown (.md) file.` };
  if (rel.startsWith('content/')) {
    return { error: `"${rel}" is a site page. Edit it with: npm run page:edit -- ${rel} "<instruction>"` };
  }
  if (GENERATED.has(rel)) return { error: `${rel} is generated. Regenerate it with: npm run changelog` };
  const top = rel.split('/')[0];
  if (SKIPPED_DIRS.has(top) || rel.split('/').some((part) => part.startsWith('.'))) {
    return { error: `Won't touch "${rel}": ${top}/ isn't hand-edited markdown.` };
  }
  const full = path.join(ROOT, rel);
  if (!fs.existsSync(full) || !fs.statSync(full).isFile()) return { error: `${rel} does not exist.` };
  if (fs.statSync(full).size > MAX_FILE_BYTES) {
    return { error: `${rel} is over ${MAX_FILE_BYTES / 1024} KB, too long for Claude to rewrite in one reply.` };
  }
  return { rel, full };
}

/* --------------------------------------------------------------- prompts */

/** What Claude needs to know about the files other scripts read. */
function fileNotes(rel) {
  if (rel === SCHEDULE_FILE) {
    return `This file is read by scripts/scaffold-schedule.js. The \`\`\`json fenced block that holds a JSON array is the live job list: it must stay one valid JSON array of job objects. Jobs with "done": true have already run; leave them exactly as they are unless the instruction is about them. Other \`\`\`json blocks in the prose are examples, not jobs.`;
  }
  if (rel === TREE_FILE) {
    return 'This file is read by scripts/scaffold-tree.js. Every page is one bullet: "- path.html", optionally followed by " — " and an instruction for Claude. Indentation is for readability only. Keep that format for every page line, and keep paths ending in .html.';
  }
  if (rel.startsWith(TREE_CONTENT_DIR)) {
    return 'This file is copied verbatim into content/ as a site page by scripts/scaffold-tree.js. Keep its "---" frontmatter block valid (flat "key: value" lines, lists as "- item"), and keep any {{ … }} template syntax intact.';
  }
  return '';
}

function buildPrompts(rel, instruction, original) {
  const notes = fileNotes(rel);
  const systemPrompt = `You edit one markdown file in the repository of the ${site.name} website, which is built by a static site generator. You are given the file's complete current contents and an instruction.

Return the complete updated file between <file> and </file>, and nothing else: no commentary before or after, no \`\`\` fence around it.

Change only what the instruction asks for. Keep everything else exactly as it is: headings, wording, line wrapping, lists, links, code blocks, frontmatter and any JSON. Match the file's existing voice. Use British spelling, sentence case headings and plain verbs; no exclamation marks. Don't invent facts, statistics or client names: if the instruction needs a detail the file doesn't have, write around it.${notes ? `\n\n${notes}` : ''}`;
  // A file in knowledge/ is already the whole prompt's subject, so it isn't sent twice.
  const withKnowledge = knowledge ? knowledge.withKnowledge(systemPrompt, { skip: knowledge.isKnowledgeFile(rel) }) : systemPrompt;

  const userPrompt = `File: ${rel}

Instruction: ${instruction}

<current_file>
${original}
</current_file>`;
  return { systemPrompt: withKnowledge, userPrompt };
}

/** The file from Claude's reply, and whether it was wrapped the way it was asked to be. */
function extractFile(text) {
  const tagged = /<file>\r?\n?([\s\S]*?)\r?\n?<\/file>/.exec(text);
  if (tagged) return { content: tagged[1], tagged: true };
  return { content: stripFence(text.replace(/^<file>\r?\n?/, '')), tagged: false };
}

/* ---------------------------------------------------------------- checks */

const fenceCount = (text) => (text.match(/^\s{0,3}(```|~~~)/gm) || []).length;
const hasFrontmatter = (text) => /^﻿?---\r?\n/.test(text);
const closedFrontmatter = (text) => /^﻿?---\r?\n[\s\S]*?\r?\n---(\r?\n|$)/.test(text);

function checks(rel, original, updated) {
  const problems = [];
  const warnings = [];

  if (!updated.trim()) problems.push('the reply is empty');
  if (updated === original) warnings.push('Claude returned the file unchanged');
  if (fenceCount(updated) % 2 === 1 && fenceCount(original) % 2 === 0) problems.push('a ``` code fence is left open');
  if (hasFrontmatter(original) && !closedFrontmatter(updated)) {
    problems.push('the frontmatter block ("---" … "---") is missing or unterminated');
  }
  if (updated.length < original.length / 2) {
    warnings.push(`the file shrank from ${original.length} to ${updated.length} characters`);
  }

  if (rel === SCHEDULE_FILE) {
    let before = null;
    try {
      before = parseJobs(original);
    } catch {
      // Already unreadable: whatever Claude returns can't be worse.
    }
    try {
      const after = parseJobs(updated);
      if (before && before.length !== after.length) warnings.push(`the job list went from ${before.length} to ${after.length} jobs`);
      if (before) {
        const doneBefore = before.filter((job) => job.done).map((job) => JSON.stringify(job));
        const afterSet = new Set(after.map((job) => JSON.stringify(job)));
        const changed = doneBefore.filter((job) => !afterSet.has(job)).length;
        if (changed) warnings.push(`${changed} job${changed === 1 ? '' : 's'} already marked done changed or disappeared`);
      }
    } catch (error) {
      if (before) problems.push(`the schedule's job list no longer parses: ${error.message}`);
    }
  }

  if (rel === TREE_FILE) {
    const before = new Set(treePaths(original));
    const after = new Set(treePaths(updated));
    if (before.size && !after.size) problems.push('the site tree has no page lines left');
    const removed = [...before].filter((p) => !after.has(p));
    const added = [...after].filter((p) => !before.has(p));
    if (removed.length) warnings.push(`pages removed from the tree: ${removed.join(', ')}`);
    if (added.length) warnings.push(`pages added to the tree: ${added.join(', ')}`);
  }

  return { problems, warnings };
}

/* ------------------------------------------------------------------- run */

/**
 * The work-log summary of a change, when the copy's lib/knowledge.js can write
 * one (older ones can't, and changes to knowledge/ aren't logged). Also made
 * for a preview with --proposal-out: the web app logs the change on apply.
 */
function summarize(rel, instruction, before, after) {
  if (!knowledge?.summarizeChange || knowledge.isKnowledgeFile(rel)) return Promise.resolve([]);
  console.log('  Writing the work-log summary…');
  return knowledge.summarizeChange({ apiKey, model: site.automation.model, command: 'md:edit', file: rel, instruction, before, after });
}

function writeProposal({ rel, instruction, content, problems, warnings, summary = [] }) {
  const target = path.resolve(ROOT, String(proposalOut));
  if (!target.startsWith(ROOT + path.sep)) {
    console.error(`  --proposal-out must be inside the repository, not ${proposalOut}.`);
    return;
  }
  const proposal = {
    file: rel,
    mode: 'markdown',
    instruction,
    images: [],
    content,
    problems,
    warnings,
    ...(summary.length ? { summary } : {}),
    model: site.automation.model,
    createdAt: new Date().toISOString(),
  };
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, `${JSON.stringify(proposal, null, 2)}\n`);
  console.log(`\n  Saved the proposal to ${path.relative(ROOT, target).replace(/\\/g, '/')}`);
}

async function run({ rel, full }, instruction) {
  console.log(`\n  File: ${rel}`);
  console.log(`  Instruction: ${instruction}`);

  const original = fs.readFileSync(full, 'utf8');
  const eol = original.includes('\r\n') ? '\r\n' : '\n';
  const { systemPrompt, userPrompt } = buildPrompts(rel, instruction, original.replace(/\r\n/g, '\n'));

  if (!apiKey) {
    console.log(`\n----- system prompt -----\n${systemPrompt}\n\n----- user prompt -----\n${userPrompt}\n`);
    console.log('  No ANTHROPIC_API_KEY set, so nothing was sent.\n');
    return dryRun ? 0 : 1;
  }

  console.log(`  Model: ${site.automation.model}\n`);
  const reply = await requestClaude({ systemPrompt, userContent: userPrompt });
  if (reply.stopReason === 'refusal') {
    console.error('  Claude declined this request. Rephrase the instruction and try again.\n');
    return 3;
  }

  const extracted = extractFile(reply.text);
  let updated = extracted.content.replace(/\r\n/g, '\n');
  updated = `${updated.replace(/\n+$/, '')}\n`.replace(/\n/g, eol);
  const { problems, warnings } = checks(rel, original, updated);
  if (reply.stopReason === 'max_tokens') problems.unshift(`Claude's reply was cut off at ${MAX_TOKENS} tokens, so the file is incomplete`);
  else if (!extracted.tagged) warnings.push("Claude didn't wrap the file in <file> tags; check the start and end for stray commentary");

  if (dryRun) {
    console.log(`----- proposed ${rel} (not written) -----\n`);
    console.log(updated);
    if (problems.length) console.log(`  problem: ${problems.join('\n  problem: ')}`);
    if (warnings.length) console.log(`  warning: ${warnings.join('\n  warning: ')}`);
    if (proposalOut) writeProposal({ rel, instruction, content: updated, problems, warnings, summary: await summarize(rel, instruction, original, updated) });
    console.log('');
    return 0;
  }

  if (problems.length) {
    console.error(`  Refused to write — looked wrong:\n${problems.map((p) => `    - ${p}`).join('\n')}\n\n  Re-run with --dry-run to inspect the output, or rephrase the instruction.\n`);
    return 3;
  }

  fs.writeFileSync(full, updated);
  knowledge?.recordWork({ command: 'md:edit', file: rel, instruction, summary: await summarize(rel, instruction, original, updated) });
  for (const warning of warnings) console.log(`  warning: ${warning}`);
  console.log(`  Wrote ${rel}  (${original.split('\n').length} -> ${updated.split('\n').length} lines)`);
  console.log(`  Review with: git diff -- ${rel}\n`);
  return 0;
}

if (flag('list')) {
  console.log(`\n  Markdown files npm run md:edit can change (site pages under content/ use npm run page:edit):\n`);
  for (const file of editableFiles()) console.log(`  ${file}`);
  console.log('');
  process.exit(0);
}

const [fileArg, instructionArg] = positional;
if (!fileArg || !instructionArg?.trim()) {
  console.error(`
  Usage:
    node scripts/edit-md.js <file> "<instruction>"             edit a markdown file with Claude
    node scripts/edit-md.js <file> "<instruction>" --dry-run   print the result, write nothing
    node scripts/edit-md.js --list                             list the files it can edit
`);
  process.exit(1);
}
const target = resolveTarget(fileArg);
if (target.error) {
  console.error(`\n  ${target.error}\n`);
  process.exit(1);
}
if (!apiKey && !dryRun) {
  console.error('\n  ANTHROPIC_API_KEY is not set. Add it to .env or your environment.\n');
  process.exit(1);
}

run(target, instructionArg.trim())
  .then((code) => process.exit(code))
  .catch((error) => {
    console.error(`\n  Edit failed: ${error.message}\n`);
    process.exit(1);
  });
